# DATA 5610: Advanced Machine Learning for Analytics {-}

## Course Information {-}

- Spring Semester 2022
- Course Dates: January 10 - May 4, 2022
- Course Time: MW 9:00 - 10:15 AM 
- Course Room: EBB 120
- [Slack Channel]()
- [Canvas Page]()


## Intructor Information {-}

- [Tyler J. Brough](broughtj.github.io)
- Office Hours: By Appointment
- Office: BUS 512
- Email: tyler.brough@usu.edu

## Course Description {-}

This course provides a foundational understanding of predictive modeling, machine learning, and data analysis for business and economic decision making. The focus of the class is on practical applications rather than deep theoretical development. Theory will be introduced to support successful implementation. 

The main purpose of the course is to foster three modes of thought to enable you to become competent scholars of business data analytics:

1. __Computational logic:__ Computational thinking helps break a problem down and find a practical path to successful implementation. Important techniques from computational mathematics and
   statistics will be introduced as they pertain to data analysis.
   
2. __Statistical logic:__ The main focus of the course will be learning to think statistically about problems in business analytics. All meaningful problems in data analysis are necessarily embedded in conditions of uncertainty. There exists a core statistical logic that is distinct from the mathematical details. Learning to develop this mode of thinking is an essential step in the life of any successful business data analyst. We will find that statistical reasoning is essential for proper business decision making. 

3. __Economic logic:__ Arbitrage is the central underlying concept of all of economics and finance. Developing skills in economic reasoning is an essential element in business data analytics.

These three ways of thinking are not independent. Quite to the contrary, we will find that they are strongly mutually reinforcing.


## Method of Teaching and Learning {-}

This course will be taught as a graduate seminar style course. __That means that your preparation and participation is crucial.__ We will get out of this course what we individually and collectively put into it. 

We will follow the Socratic Method during lectures. A good amount of class time will also be dedicated to guided computational exploration. The idea behind this exploration is to develop a methodology for __computational thinking__. Mathematical theory will serve as an important background to this enterprise but will not itself be the focus. 

___Your preparation and participation is absolutely essential to the success of this course!___


## Assessment {-}

The grade that you will earn will be determined by the weighted total points accumulated. The weights given to each part of the class are as follows:

* _Class Preparation & Participation (10%)_ - In a Socratic style seminar student preparation and participation is essential!

* _Student Presentations (10%)_ - Throughout the course a set of specialized readings will be distributed. Each student will have an opportunity to prepare a presentation to the class on one or more of the assigned readings. 

* _Annotated Bibliography & Wiki-style Articles (15%)_ 
	- Throughout the course, a set of specialized readings will be distributed. Each student will prepare an annotated bibliography of each reading.
	- Students will prepare a Wikipedia-style summary article on one specialized topic from each of the four areas of concentration. The following are examples (not exhaustive) of topics that might be chosen:
		1. Decision theory: sequential analysis, utility and loss functions, risk analysis, etc.
		2. Supervised learning: pattern classification, Lasso regression, Random forests, etc.
		3. Time series analysis: cointegration and error-correction, time series bootstrap methods, hidden markov models, etc.
		4. Reinforcement learning: k-armed bandits, Thompson sampling, AlphaZero, etc.

* _Projects (65%):_
	- Kaggle Titanic classification (16.25%) - [Kaggle Titanic - Machine Learning from Disaster](https://www.kaggle.com/c/titanic)
	- Stock returns prediction (16.25%)
	- Pairs trading prediction (16.25%)
	- Auction/Reinforcement learning simulation (16.25%)
	
* _Extra Credit:_ There will several opportunities for extra credit work. 


## Communications {-}

We will use Canvas only to share documents and for certain communications. 

For all other communication purposes we will use a course Slack channel. Students will receive an invitation to the Slack the first week of class. You should check for communications and announcements often. 


## Readings {-}

Unfortunately, there is no single source that covers all of the topics that we will cover in this course.  The readings and a reading schedule will be distributed through the course Canvas page. We will take readings from the following sources.

* [Analysis of Integrated and Cointegrated Time Series with R][Pfaff] by Bernhard Pfaff

* [An Introduction to Statistical Learning: with Applicaitons in R][JamesWittenHastieTibshirani] by James, Witten, Hastie & Tibshirani

* [Applied Predictive Modeling][KuhnJohnson] by Kuhn & Johnson

* [Computational Statistics Handbook with MATLAB][MartinezMartinez] by Martinez & Martinez

* [Economic Forecasting][ElliotTimmermann] by Elliot & Timmermann
 
* [Introduction to Machine Learning][Alpaydin] by Ethem Alpaydin


While these are the main sources there will be additional sources distributed in addition to the above. 


## Topics {-}

We will cover the following main modules:

1. Introduction to statistical decision theory
2. Supervised learning
3. Time series analysis
4. Reinforcement learning 

<br>

### Import dates {-}

* __First day of classes__ - Jan 10
* __Martin Luther King, Jr. Day__ - Jan 17
* __Presidents' Day__ - Feb 21
* __Spring Break__ - Mar 7 - 11
* __Last day of classes__ - Apr 26
* __Final exams__ - Apr 28 - May 4


[Alpaydin]: https://www.cmpe.boun.edu.tr/~ethem/i2ml3e/
[ElliotTimmermann]: https://press.princeton.edu/books/hardcover/9780691140131/economic-forecasting
[JamesWittenHastieTibshirani]: https://www.statlearning.com/
[KuhnJohnson]: http://appliedpredictivemodeling.com/
[MartinezMartinez]: https://www.routledge.com/Computational-Statistics-Handbook-with-MATLAB/Martinez-Martinez/p/book/9781466592735
[Pfaff]: https://link.springer.com/book/10.1007/978-0-387-75967-8