## The Pairs Trading Project {-}

\vspace{5mm}

### Project Description {-}

This project is based on the research article *Illuminating the
Profitability of Pairs Trading: A Test of the Relative Pricing
Efficiency of Markets for Water Utility Stocks* by @GutierrezTse2011
(GT). GT examine the profitability of the basic pairs trading strategy.
This strategy relies on identifying pairs of assets that are
cointegrated. GT study stocks in the water utility industry in the hopes
that pairs of them will be cointegrated.

\vspace{3mm}

Your assignment is to reproduce Exhibit 2 Panel A and Panel B, as well
as Exhibit 3 (all panels) for three stocks that they choose. The
deliverable is a Jupyter notebook with Python (or R, Julia, or
whatever) code that carries out the calculations. You should make tables
of the results in your document and write several paragraphs of prose to
explain the results.

\vspace{3mm}

This project does not require you to carry out the analysis for the
actual trading strategy. Instead, you are required to discuss how the
results you found in your analysis of cointegration and error-correction
enable you to form such strategies. Outline a strategy of how you would
use the predictive analytics and statistical foundation from your analysis to set up and carry
out pairs trading strategies in real life. What factors need to be
considered when going from predictive models to real life trading? What
data, systems, or other factors need to be considered? How does having
an predictive analytics foundation aid the process? What other machine learning or
econometric methods or procedures would aid your plan? What concerns
about the process do you forsee as the portfolio manager?

\pagebreak
